### ISSUE TITLE
Login into Google Account using Microsoft SSO

### ISSUE THREAD

**Issue by andreduartesp** [ferdium/ferdium-app#1128]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.2.7-nightly.4

### What Operating System are you using?

macOS

### Operating System Version

Ventura 13.3.1 (22E261)

### What arch are you using?

x64

### Last Known Working Ferdium version

6.2.7-nightly.4

### Expected Behavior

Add any service with Google Login (including Gmail, Google Calendar, Google Drive) and be able to log in using Microsoft SSO

### Actual Behavior

When I try to log in into Google Account using Microsoft SSO, I get error 405 after I came back from Microsoft login.

### Steps to reproduce

1. Click in add service
2. Search for any Google service (or service using Google SSO)
3. Try to log in using an account with Microsoft SSO
4. Get error 405 from Google

### Debug link

https://debug.ferdium.org/33ffee9b-cfb2-4036-b225-c0ad66c42a5c

### Screenshots

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8616468/234177754-1886bd78-a12f-46aa-825d-9cce1bc6e60d.png">

**Comment by vraravam** [comment]
What's the behavior when using the same procedure but in a regular browser? IF this behavior is consistent in the regular browser, then we can't really do much in Ferdium.

**Comment by andreduartesp** [comment]
> What's the behavior when using the same procedure but in a regular browser? IF this behavior is consistent in the regular browser, then we can't really do much in Ferdium.

Sorry about the delay, in any browser  I've tried (Chrome, Safari, Firefox, Konqueror and Opera) the login was completed with success. I tried the same process with Franz, and worked too.

**Comment by andree392** [comment]
I think I'm experiencing the same issue but im using Google Chat with jumpcloud.com login.

I've tried adding/removing Google Chat, clearing the cache etc. still only gives me the same error as @andreduartesp got, 405 malformed request.

I can confirm that it works as expected in a normal browser window but unable to get it working in ferdium.

[debug link](https://debug.ferdium.org/2047cef4-8ac2-4713-8366-d1dfd31f7698)

Let me know if i can do anything to help troubleshoot.

**Comment by ftenaglia** [comment]
I have the same issue with Google login (gmail, calendar and so on) via Okta SSO. It works fine on Chrome/Firefox

**Comment by afvieira** [comment]
I have the same problem.

Info about Ferdium version:

> Version: 6.4.1
> Server: Ferdium Server
> Electron: 25.5.0
> Chrome: 114.0.5735.289
> Node.js: 18.15.0
> Platform: macOS Monterey
> Arch: x64
> Build date: Tue Aug 15 2023 14:45:59 GMT+0100 (Western European Summer Time)
> Git SHA: 09ee519f
> Git branch: release

**Comment by andree392** [comment]
So i was looking into this a bit more, for me the 405 link is 

> https://accounts.google.com/samlrp/acs?rpid=ID

found some info here
[Google Cloud Single Sign on](https://cloud.google.com/architecture/identity/single-sign-on#configuration)

not really sure what needs to change
guessing that url needs to be added to [webview.js](https://github.com/ferdium/ferdium-recipes/blob/main/recipes/hangoutschat/webview.js) 
ill see if i can play around with it later.

**Comment by SpecialAro** [comment]
Hey! This issue is possibly fixed in the latest stable (if you have an `arm64` computer don't update, we are having issues with that build).
Or use the latest nightly (again, not for `arm64`)

**Comment by trackd** [comment]
It's still broken on version `6.5.1`, so not fixed yet unfortunately.

i think atleast for my problem there needs to some handling of these values

> The external IdP returns a specially crafted HTML page that causes your browser to immediately send an HTTP POST request to the ACS URL. This request contains two parameters:  
> 
> - RelayState, which contains the value originally passed to the IdP in the SAML authentication request.  
> - SAMLResponse, which contains the base64-encoded SAML assertion. The SAML assertion is an XML document that states that the IdP has successfully authenticated the user. In decoded form, the SAML assertion looks similar to the following:  

```xml

<samlp:Response ...>
  ...
  <Assertion x...>
    <Issuer>https://idp.example.org/</Issuer>
    <Signature ...>
      ...
    </Signature>
    <Subject>
      <NameID Format="...:nameid-format:emailAddress">bob@example.org</NameID>
      ...
    </Subject>
    <Conditions NotBefore="..." NotOnOrAfter="...">
      <AudienceRestriction>
        <Audience>google.com</Audience>
      </AudienceRestriction>
    </Conditions>
    <AttributeStatement>
      ...
    </AttributeStatement>
    <AuthnStatement AuthnInstant="..." ...>
      <AuthnContext>
        <AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</AuthnContextClassRef>
      </AuthnContext>
    </AuthnStatement>
  </Assertion>
</samlp:Response>
```
[from google docs](https://cloud.google.com/architecture/identity/single-sign-on)

it is a bit strange because this works fine in a browser..

**Comment by sjoubert** [comment]
Hi, I'm hitting this issue also (same behavior and 405 error), using version 6.7.3

**Comment by waldman** [comment]
Hi guys, hitting the same bug with version 6.7.4 on Okta SSO.

**Comment by vitorhugods** [comment]
I guess Ferdium doesn't behave well with Google Login + SSO in general. Can't use Calendar or Gmail with Jumpcloud SSO on v7.0.0

**Comment by soukron** [comment]
For whoever arrives here: still not fixed in version 7.1.1 on MacOS.

**Comment by jonrick** [comment]
Running into this same issue this morning, using OKTA SSO - can't seem to work around it.

I even made the jump to 7.1.2-nightly.3 and still getting it there.

I had been using the workaround found in: https://github.com/ferdium/ferdium-app/issues/1973 for the blank screen after login, but can't do that now that I'm getting the 405 error instead.

**Comment by unclamped** [comment]
figured out a workaround, although this was only for my institution's gmail account. should still work for this.
full disclosure, this was 95% done with AI. I did not give enough of a fuck to write this nor learn about websockets on my own.

1. download any extension that will give you a cookies.txt file (in the case of firefox, use [this](https://addons.mozilla.org/en-US/firefox/addon/get-cookies-txt-locally/) or if in chrome, [this](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc?pli=1)
2. enable the extension to be used in incognito tabs
3. open an incognito tab and log in as usual to said service
4. grab the cookies.txt for ALL sites, just in case. it's not like there's gonna be extra cookies anyways, since this is incognito.
5. completely kill ferdium. pkill -f ferdium or just right click the tray icon and quit it.
6. write to a python file in the same dir as the cookies.txt the following:
```py
import json
import requests
import websocket
import sys
import os

if not os.path.exists('cookies.txt'):
    print("Error: 'cookies.txt' not found in current directory.")
    sys.exit(1)

cookies = []
with open('cookies.txt', 'r') as f:
    for line in f:
        line = line.strip()
        if not line: continue
        
        # Handle the HttpOnly flag prefix common in Netscape exports
        http_only = False
        if line.startswith('#HttpOnly_'):
            http_only = True
            line = line[10:]
            
        if line.startswith('#'): continue
        
        parts = line.split('\t')
        if len(parts) >= 7:
            domain = parts[0]
            path = parts[2]
            # CDP often strictly requires a URL along with the domain
            url_scheme = "https://" if parts[3].upper() == "TRUE" else "http://"
            url = f"{url_scheme}{domain.lstrip('.')}{path}"

            cookie = {
                "url": url,
                "domain": domain,
                "path": path,
                "secure": parts[3].upper() == "TRUE",
                "name": parts[5],
                "value": parts[6],
                "httpOnly": http_only
            }
            
            # Handle session vs persistent cookies
            try:
                exp = int(parts[4])
                if exp > 0:
                    cookie["expires"] = exp
            except ValueError:
                pass

            cookies.append(cookie)

print(f"[*] Parsed {len(cookies)} cookies from file.")

# Connect to the local Ferdium debugging port
try:
    res = requests.get("http://127.0.0.1:9222/json")
    targets = res.json()
except requests.ConnectionError:
    print("[!] Failed to connect. Is Ferdium running with --remote-debugging-port=9222?")
    sys.exit(1)

# Filter targets to find only active service pages/webviews
pages = [t for t in targets if t.get('type') in ['page', 'webview']]

print("\nAvailable Ferdium Services:")
for i, p in enumerate(pages):
    title = p.get('title', 'Unknown Title')
    print(f"[{i}] {title}")

try:
    choice = int(input("\nEnter the number of the service to inject cookies into: "))
    target = pages[choice]
except (ValueError, IndexError):
    print("[!] Invalid choice.")
    sys.exit(1)

print(f"\n[*] Injecting cookies into: {target.get('title')}...")
ws = websocket.create_connection(target['webSocketDebuggerUrl'])

# Send the CDP command
payload = {
    "id": 1,
    "method": "Network.setCookies",
    "params": {
        "cookies": cookies
    }
}

ws.send(json.dumps(payload))
result = json.loads(ws.recv())

if "error" in result:
    print(f"[!] Injection Error: {json.dumps(result['error'], indent=2)}")
else:
    print("[+] Success! Go to Ferdium and refresh (Ctrl+R) the service tab.")

ws.close()
```
7. launch ferdium like this: `ferdium --remote-debugging-port=9222 --remote-allow-origins=*`
8. run the python script, select the tab you want to override the session cookies to
9. close ferdium again completely
10. reopen it
11. ???
12. profit
