### ISSUE TITLE
Is it possible to force Ferdium to activate a specified service?

### ISSUE THREAD

**Issue by oversider-kosma** [ferdium/ferdium-app#1243]
### Your issue

Is there a way to launch Ferdium (or switch an already running instance) to a specific service using a command line argument, a DBus call, or any other method accessible from outside the application?

**Comment by orgrimarr** [comment]
I saw this on the source code, it seams related but I'm not sure about that.

- https://github.com/orgrimarr/ferdium-app/blob/3ae8a2387f0120736689777851a7c234c68ee4b7/src/stores/AppStore.ts#L230
- https://github.com/orgrimarr/ferdium-app/blob/develop/src/electron/deepLinking.ts

Using this cmd on Mac, it opens the app and navigate to something but I din't manage to make it work as expected.

```shell
open ferdium://something
```

**Comment by orgrimarr** [comment]
Seams to have a dbus api, but it can't open a specific service. https://github.com/ferdium/ferdium-app/blob/develop/docs/DBUS.md
Same for `ferdium://` https://github.com/orgrimarr/ferdium-app/blob/3ae8a2387f0120736689777851a7c234c68ee4b7/src/stores/AppStore.ts#L230


But , I think, this feature can be easily implemented. I haven't take a look at the dbus API, but using ferdium:// deep link feature, we can extends the behavior by adding an handler for this kind a route `Ferdium://services/:serviceId` for example.

Then we can use the service store to toggle the right service.

```javascript
this.stores.services._setActive({
  serviceID: '0d7a401e-52e9-4d6b-883c-3e61eafc3af1',
});
```
This example uses a private method of the store. But it demonstrate the feasibility.

**Comment by SpecialAro** [comment]
Hey 😊

Indeed @orgrimarr , that is the way of implementing this, thank you.

I've made some code locally that works by handling deep links and activating the correct service. The only issue so far is that the user has to know the service id so as to run that function, which limits usability.

Nevertheless, when I get the time, I'll try to implement something like navigating with a recipe name instead of id (and if there is more than one with the same name, ask the user which one to use). What do you think about it?

**Comment by mdbraber** [comment]
Having deeplink functionality would still be helpful. Would it be possible to re-open this issue?

**Comment by SpecialAro** [comment]
Hello @mdbraber ,

As you can see per the issue status, the issue was closed because I pushed a PR that got merged that allows deep linking to a service inside Ferdium 😁

**Comment by KrystianLesniak** [comment]
Hi @SpecialAro .

It's been a while, so it's hard for me to remember, but if I recall correctly, it still isn't working/fixed for the Windows OS. More details are available here:
https://github.com/ferdium/ferdium-app/pull/1344#issuecomment-1705126732

**Comment by SpecialAro** [comment]
> Hi @SpecialAro .
> 
> It's been a while, so it's hard for me to remember, but if I recall correctly, it still isn't working/fixed for the Windows OS. More details are available here:
> https://github.com/ferdium/ferdium-app/pull/1344#issuecomment-1705126732

I'll go take a look but I find it hard for it not to be working because I was the one that implemented it and I use a Windows machine 😅 but I'll check it out and get back to you.

**Comment by mdbraber** [comment]
Thanks @SpecialAro I've found the implemented code - I thought another PR had retracted the changes, but was happy to see it's in there!

**Comment by mdbraber** [comment]
@SpecialAro I'm using this functionality daily and it works great. Can I also use this or something similar to open links in a specific service? E.g. I'm using a custom website 'https://forum.xyz' and I want to open 'https://forum.xyz/post` in that service

It would be best if Ferdium would act as a `https` URL handler and process these URLs by looking up the services for a URL pattern match (and if not found: redirect to the default browser). That would let people use tools like Choosy and Hammerspoon to redirect URLs 

Alternatively a pattern of `ferdium://link/<url>` or similar could be used to process links
