### ISSUE TITLE
Whatsapp keeps giving unread messages (but everything is readed)

### ISSUE THREAD

**Issue by mrgix** [ferdium/ferdium-app#1471]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6,6,1-nightly.14

### What Operating System are you using?

macOS

### Operating System Version

Sonoma 14.1.2

### What arch are you using?

x64

### Expected Behavior

When you start up fedrium and all messages are readed it not keeps you giving a notification of 79 messages not readed. 

### Actual Behavior

Whatsapp keeps holding a notification number of unread messages. But all messages are readed. 
Somewhere there are messages not readed. But if you filter on give me unreaded messages nothing shows up.
Mobile phone app also says that everything is readed.
Due to this isue i also get the badge on the ferdium icon on the task bark
![image](https://github.com/ferdium/ferdium-app/assets/6233470/fccbb83c-152a-4cb8-895b-6c1cddfc97b0)

### Steps to reproduce

Just opening the app and the notification gives you notification of 79 messages readed. But everything is readed when you filter on readed messages. 

### Screenshots

![image](https://github.com/ferdium/ferdium-app/assets/6233470/82d3118c-069a-4854-9240-d26932f1eba4)

**Comment by pulver22** [comment]
The same is present on the Linux version (PopOS 22.04).

**Comment by max1c** [comment]
Interestingly enough, I don't get any notification badges on whatsapp.

**Comment by Richardvi** [comment]
I have the same problem on Windows 11. I have two Whatsapp accounts, one personal and ons business. The personal account always shows something unread, specially on the tray icon of Ferdium. When I look at the Whatsapp messages, they all seem read. No unread messages.

![image](https://github.com/ferdium/ferdium-app/assets/5486910/3f098b69-7ba7-4c5a-9f76-373b59c57f9a)

![image](https://github.com/ferdium/ferdium-app/assets/5486910/b306ff3d-3b44-4f10-91a4-feff9c2fbc17)

**Comment by SpecialAro** [comment]
Hi @mrgix, can you please post which version of the Whatsapp service are you running?

Right-click the service > Edit > Scroll down to the bottom of the screen

**Comment by mrgix** [comment]
![image](https://github.com/ferdium/ferdium-app/assets/6233470/defa5310-6b3c-476b-a0bb-8eb1abf80243)
 
![image](https://github.com/ferdium/ferdium-app/assets/6233470/b841d5d6-9ac4-461e-babb-1655339532aa)

**Comment by mrgix** [comment]
![image](https://github.com/ferdium/ferdium-app/assets/6233470/a4d4fa0b-cd7c-4ee1-a28d-3780e1078756)
Looks like it has been fixed! Lets see for the next couple of days!

**Comment by igitur** [comment]
Still a problem for me. 

![image](https://github.com/ferdium/ferdium-app/assets/145854/4e460285-d10e-4fee-8463-14767a91db54)


Version: 6.7.1-nightly.9
Server: No Server
Electron: 28.1.3
Chrome: 120.0.6099.199
Node.js: 18.18.2
Platform: Windows 10
Arch: x64
Build date: Wed Jan 17 2024 02:49:11 GMT+0200 (South Africa Standard Time)
Git SHA: 2ac56e6f
Git branch: nightly

**Comment by mrgix** [comment]
And the bug is back again:
<img width="457" alt="image" src="https://github.com/ferdium/ferdium-app/assets/6233470/6b6bd11b-5e05-47cb-9521-430718df4b7d">
<img width="326" alt="image" src="https://github.com/ferdium/ferdium-app/assets/6233470/5d5c26a4-81e3-4b95-a359-00408c5cc0ad">

**Comment by mrgix** [comment]
Any updates on this bug? Still got this problem...

**Comment by AndrewWPhillips** [comment]
I had the same problem on Windows after I manually marked a chat as unread at one stage.  Much later the start and taskbar icons shows (1) unread but *none* of the chats were showing as unread.  I manually marked a few of the chats as read then marked them as unread again and it fixed the issue.

**Comment by peio72** [comment]
still having the bug with 1 unread in whatsapp, none into the official app

**Comment by SirLogician** [comment]
I had the same problem and in my incident it was "locked chat" that was causing the issue. Locked chat notification does not appear in original whatsapp but rambox displays it. So I unlocked the chat, read that message and issue is fixed.

**Comment by 3c7b1b91-0c9d-40a8-88bf-6e3c7f28b3e5** [comment]
> I unpinned Whatsapp from my taskbar and then repinned it and that fixed the problem for me.

You're a lifesaver.
