### ISSUE TITLE
White screen when using Ferdium for more than a few hours. Reboots fix it. 

### ISSUE THREAD

**Issue by mattfaraday** [ferdium/ferdium-app#1605]
### Avoid duplicates

- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-app/blob/HEAD/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22bug+%3Abeetle%3A%22) for a bug report similar to mine, in vain

### Ferdium Version

6.7.0

### What Operating System are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04 LTS

### What arch are you using?

x64

### Expected Behavior

I expect to see my services (Telegram, Whatsapp etc). 

### Actual Behavior

I see white windows with nothing in them after using for some time. If I reboot it fixes it. Restarting the app doesn't. 
![Screenshot from 2024-03-07 15-36-47](https://github.com/ferdium/ferdium-app/assets/10899266/fdf73ee6-eabd-46c3-855a-c51b3ca393a5)

### Steps to reproduce

1. Install Ferdium on Ubuntu 22.04 LTS
2. Setup Telegram and Whatsapp
3. After several hours of use, or days of suspending a machine instead of turning it off, Ferdium will show these white pages

### Screenshots

![Screenshot from 2024-03-07 15-36-47](https://github.com/ferdium/ferdium-app/assets/10899266/c0ae0e7c-3360-4a64-a259-c257715f1970)

### Additional information

Ubuntu 22.04 LTS
Thinkpad T480
GNOME 42.9
Intel UHD Graphics 620

**Comment by lguerard** [comment]
I can reproduce this for Whatsapp (all the rest of my services work ok). I'm on Mint 21.3 (based on Ubuntu 22.04 as above).

**Comment by SpecialAro** [comment]
Hello @lguerard and @mattfaraday.

Can you please confirm the Ferdium version you are on?

**Comment by lguerard** [comment]
It was the snap version so  6.7.1 I think. I uninstalled it since to install a more up to date version so can't really check anymore unfortunately..

**Comment by mattfaraday** [comment]
It was 6.7.0 for me. I'm also not using it right now / uninstalled.

**Comment by SpecialAro** [comment]
Ok thank you. I'll assume this is fixed given that there is no reported issues on the latest stable.

**Comment by magiodev** [comment]
I still experience this, but right-clicking the service in the left navbar and reloading works (or just CTRL+R).

```
Version: 7.0.0
Server: No Server
Electron: 33.2.0
Chrome: 130.0.6723.118
Node.js: 20.18.0
Platform: Linux 6.8
Arch: x64
Build date: Sun Nov 10 2024 03:22:25 GMT+0100 (Central European Standard Time)
Git SHA: e6249427
Git branch: release
```

Worth mentioning that this only happens with Telegram, but I’m only using WhatsApp and Telegram, so this might not be enough data to draw a conclusion.
