### ISSUE TITLE
Bug: Whatsapp web keeps reloading

### ISSUE THREAD

**Issue by TheMoltenJack** [ferdium/ferdium-app#310]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly.69

### What Operating System are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

Whatsapp should not reload at every interaction with the interface.

### Actual Behavior

Every time I interact with Whatsapp web the page stays unresponsive for a couple of seconds and the loading message keeps flashing until the page starts responding again. After the introduction of the line loading indicator only the indicator flashes and not the loading message. The issue is present on both Linux and Windows and both local account and synced account.

### Steps to reproduce

1. Open Ferdium
2. Open the whatsapp web service

**Comment by SpecialAro** [comment]
Hello @JacopoMolteni , thank you for logging this issue.

Are you sure you're on the latest nightly?

**Comment by jasmines** [comment]
Same here, Snap build nightly 69 on Ubuntu 22.04

**Comment by TheMoltenJack** [comment]
Hi @SpecialAro, yes, I have the latest build from AUR and have updated it manually on Windows. I have the problem since I started using Ferdium so at least 3 or 4 nightly releases.

**Comment by SpecialAro** [comment]
Just to clarify, you still see this "loading message" on nightly 69 (check the gif below)? @JacopoMolteni and @jasmines

https://user-images.githubusercontent.com/37463445/173538145-6825c727-5cda-4213-b987-b3d30f1c8441.gif

**Comment by jasmines** [comment]
No, there's no more "loading" message, but the loading bar on top of chat and contacts is flickering as soon as I change chat, after a second or two it stabilizes and I can use the chat. When I move to another chat, it does it again and again and again...

**Comment by TheMoltenJack** [comment]
@SpecialAro I am on nightly 69 but the loading screen has been replaced by a bar at the top of the page, as per changelog. The loading bar flashes for a couple of seconds meanwhile the page is not responding, then it goes back working again until I change chat or I switch to another service and go back to Whastapp again.

**Comment by SpecialAro** [comment]
> @SpecialAro I am on nightly 69 but the loading screen has been replaced by a bar at the top of the page, as per changelog. The loading bar flashes for a couple of seconds meanwhile the page is not responding, then it goes back working again until I change chat or I switch to another service and go back to Whastapp again.

Ok, now this makes sense to me.

Since nightly 69 a new feature was implemented. Please, try to "Edit" the whatsapp recipe (right-click) and uncheck this option:
![image](https://user-images.githubusercontent.com/37463445/174628725-dc693d6e-5dc1-4ff7-8429-9258ef2c5d6e.png)

Then let me know if it is solved 😄

**Comment by jasmines** [comment]
Yeah!

**Comment by TheMoltenJack** [comment]
It would seem so but I can't but feel that the page is still not as responsive as it is on browser. I'll try it out for some time and see if it's just a temporary issue.

**Comment by SpecialAro** [comment]
> It would seem so but I can't but feel that the page is still not as responsive as it is on browser. I'll try it out for some time and see if it's just a temporary issue.

This is also known to be happening... But I think it may be caused by Whatsapp itself, as @fernandofig pointed out in discord.

@fernandofig maybe if we can fix the occasional search problem we have with your version (from time to time happens to me too, I'm using your version), we can maybe raise a PR and try to workaround it with the code you made?

Nevertheless, just noticed this is maybe out of the scope of this issue, and maybe we can close it soon @JacopoMolteni, what do you think?

**Comment by fernandofig** [comment]
@SpecialAro , I'll have a look if I can kludge a workaround for the search issue later. Unfortunately the workaround for the lagging issue is already itself a kludge, and the search issue is not the only collateral for this, it's just the most noticeable and frequent one. That's why I refrained from submitting a PR for the Whatsapp recipe... well, that, and also the fact that it doesn't sit well with me to change a recipe to workaround a problem that's not on Ferdium, but rather clearly some bugged code from Meta on Whatsapp Web - which I expect / hope, at some point, to be fixed on their end, rendering that workaound stale, and so we'd need to keep tabs on it without the workaround to know when it happens.

But yes, the lagging issue is out of scope of this GH issue, it's probably better to open another one for this.

As a side comment (and possible suggestion for opening yet another GH issue), I think it would be worth it to have the progress bar setting to have a default setting exported by recipe - and in the case of Whatsapp Web, have it disabled by default, because due to the way Whatsapp Web works, the progress bar is really not useful, and actually kind of distracting.

**Comment by vraravam** [comment]
we can always make the default as "off" for the global setting @fernandofig (for the progress bar). That might be an easier solution, wouldn't it?

**Comment by fernandofig** [comment]
Easier for sure, @vraravam ! Whether the community prefers it on or off by default is another matter. I don't care much for the progress bar myself, but that's me, I don't want my own preference to be responsible for a wide-reaching decision like that :-)

(E: also, I can glimpse instances where the progress bar *might* be useful, it just isn't for me with the services I currently use on Ferdium)

**Comment by vraravam** [comment]
at this point, the community only has 1 nightly when this feature was introduced. Switching now is easier (less impact) imo.

**Comment by simonszu** [comment]
Maybe related: I was not able to move or resize the window (unmaximize or minimize, maximize works fine) while on WhatsApp with the progress bar enabled. Other recipes or disabled progress bar works fine. 
With enabled progressbar, trying to move or resize the window only causes the progress bar to flicker.

**Comment by cino** [comment]
@simonszu That specific issue has been resolved by #372 which will be in a future release.

**Comment by simonszu** [comment]
@cino OK, thanks :)

**Comment by osky85** [comment]
I think is resolved now but Whatsapp Web continues to be unresponsive, the "loading messages" are now hidden but the UI still freezes for a couple of seconds after some particular actions.

**Comment by SpecialAro** [comment]
> I think is resolved now but Whatsapp Web continues to be unresponsive, the "loading messages" are now hidden but the UI still freezes for a couple of seconds after some particular actions.

Is this what you're referring to: https://www.youtube.com/watch?v=gZ9krkI-LOc ?

I think this is related with a known bug that is due to the Whatsapp code. We have a workaround available in discord (https://discordapp.com/channels/963836780778512454/963841911376982046/984093764274516018) but it introduces other problems, although it is stable enough.

**Comment by osky85** [comment]
@SpecialAro Yes that's the problem, I don't know if there is an issue ticket on github to track that bug. I will check the workaround. Thanks!

**Comment by MagicLegend** [comment]
After updating to nightly 87 (from 67), it appears like this problem has been fixed :tada: Can others confirm this too?

**Comment by krisrok** [comment]
This is still happening for me quite often. "Something" is stealing focus from the text input field regularly. I think I can kick it out of this mode by navigating to other chats and then back. Will keep an eye on it.

**Comment by SpecialAro** [comment]
> "Something" is stealing focus from the text input field regularly

This is a known issue but has been reported also by some users using the official Whatsapp App, so I don't think this is a Ferdium Issue.

> by navigating to other chats and then back

As a workaround (thank you @vraravam), try using `TAB` and then `Shift + TAB`. This should work and you can type again right after.

**Comment by SpecialAro** [comment]
@JacopoMolteni is this issue solved after all? Should we close it?
