### ISSUE TITLE
Bug: Whatsapp Web popups get hijacked by Ferdium Warning

### ISSUE THREAD

**Issue by eitchtee** [ferdium/ferdium-app#573]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

Version: 6.0.1-nightly.17

### What Operating System are you using?

Windows

### Operating System Version

Windows 10 version 21H2

### What arch are you using?

x64

### Expected Behavior

All popup content should be displayed.

### Actual Behavior

Due to ferdium/ferdium-recipes/pull/138 Whatsapp Web popups other than the theme one gets hijacked, removing functionality.

### Steps to reproduce

1. Open a conversation
2. Try to delete a message sent by you

### Debug link

https://debug.ferdium.org/42fb4293-0162-4f6c-bad6-131b3a078f0d

### Screenshots

![image](https://user-images.githubusercontent.com/10510126/186666802-bcb4147c-1b9d-4dfa-be83-dfdf0f54c6f9.png)
The popup for deleting a message. The button to delete the message for yourself is deleted, leaving only the one for deleting to everyone.

**Comment by vraravam** [comment]
I experienced the same. The impact is that the "Report" and "Block" links get overridden/hidden due to the addition of the warning text that got injected.

**Comment by CyberDruga** [comment]
Having the same issue, I can't mute chats because of it.
![image](https://user-images.githubusercontent.com/22626848/188197560-a6b1958c-cd4a-4188-9dca-09e7e82586e5.png)

**Comment by janpelikan** [comment]
On version 6.0.1 and 6.0.0 same bug. Impacts popup when you want add person to group chat. Really annoying.

**Comment by vraravam** [comment]
Closing this ticket since the bug has been fixed in the latest nightlies.

**Comment by Yuki2DX** [comment]
Can it be re-opened then?

![2022-09-07_10 57 56_1083](https://user-images.githubusercontent.com/40588990/188916564-50a76cf3-05c8-464c-b9f1-b1689385cf67.png)
![2022-09-07_10 58 08_1084](https://user-images.githubusercontent.com/40588990/188916570-5842cad7-f4d1-47d8-8e41-94bf4726816f.png)

**Comment by SpecialAro** [comment]
I think that now the issue is another one.

You didn't got the popup to Reload Services (right?) because the Tag is wrongly placed on the repository... It is pointing to commit c6a6d172cc700fdc88f66df6726b1784b46fd617 (which has this fix) but it should be pointing to 4006d2aceb4f24075472de36a07155eec58aeb54 (which doesn't). I think this is the CI/CD fault, it is tagging the repository wrongly... Can you take a look when you have time @vraravam, just to see if you agree with me?
My guess is that the automatically nightly CI started and triggered 4006d2aceb4f24075472de36a07155eec58aeb54 but didn't tag it (probably because the TAG ALL REPOS CI failed). Then, the CI for checking and updating submodules started, which committed c6a6d172cc700fdc88f66df6726b1784b46fd617 with the fix for this issue, and tagged itself - if that's the case, we should probably remove the self-tagging for that CI.

Therefore, I think we can keep this issue closed because the next nightly will, for sure, include the fix.

**Comment by Yuki2DX** [comment]
You're right. No 'perma-loading' popups on my side.

**Comment by cjdg** [comment]
I can confirm its present on 6.1.0 Linux

**Comment by vraravam** [comment]
@cjdg - as commented earlier, this has been fixed in the latest nightlies. please do not add more comments on known issues.

**Comment by Yuki2DX** [comment]
Latest nightly. Well, it's still broken.

![2022-09-09_17 15 19_1086](https://user-images.githubusercontent.com/40588990/189447123-8b2912e0-0b27-4049-b298-e810519537d0.png)
![2022-09-09_17 15 36_1087](https://user-images.githubusercontent.com/40588990/189447126-e3ac2b01-efbb-45b1-bef9-9e01c56b9e9e.png)
![2022-09-09_17 15 57_1088](https://user-images.githubusercontent.com/40588990/189447128-4724b166-380d-4c3c-843f-e0ebc3b7b3de.png)

**Comment by vraravam** [comment]
What's the version of the Whatsapp recipe that your system has? `3.4.6` of the whatsapp recipe has this problem solved.

**Comment by Yuki2DX** [comment]
For some reason, it was v3.4.5. I fully uninstalled Ferdium, installed it once again (Same versión, latest nightly) and now it has v3.4.6 and it's just as you said: It's already fixed! Thanks!

**Comment by cjdg** [comment]
Its happening in 6.2

**Comment by vraravam** [comment]
If this is still happening with 6.2, then the only (and verified) reason is that the recipe version for WA is not the latest. Please ensure that your recipe version is 3.4.6
