### ISSUE TITLE
Bug: Custom Icons do not apply when saving

### ISSUE THREAD

**Issue by FWidm** [ferdium/ferdium-app#809]
### Avoid duplicates

- [X] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.2.1 (deb version)

### What Operating System are you using?

Ubuntu

### Operating System Version

Linux 5.15.0-10053-tuxedo

### What arch are you using?

x64

### Expected Behavior

- setting a custom icon in a service should save that icon
- if that fails the notification should not say that all settings have been saved

### Actual Behavior

- image is not stored
- no error is thrown

### Steps to reproduce

- clicking on custom icon opens the file picker
- the file is chosen and is within size limits (~10kB)
- the file is displayed within the service
- clicking on save works and redirects to the services page
- the message "your changes have been saved" shows
- the image is not applied and not saved

### Screenshots

![image](https://user-images.githubusercontent.com/3480240/204727199-b6dbe658-29ca-4b6f-890c-2286aaae8314.png)
![image](https://user-images.githubusercontent.com/3480240/204727260-a47d0795-0bde-4719-bb44-3a1d5b5ee601.png)

### Additional information

I've skipped making an account when setting up my new install

**Comment by leandrogehlen** [comment]
https://user-images.githubusercontent.com/1750751/204788426-64d688df-9b22-4bac-9372-cd7fabd99f77.mp4

**System Info**

Version: 6.2.1
Server: No Server
Electron: 21.3.1
Chrome: 106.0.5249.181
Node.js: 16.16.0
Platform: Windows 11
Arch: x64
Build date: Tue Nov 29 2022 23:57:14 GMT-0300 (Horário Padrão de Brasília)
Git SHA: a961c78e
Git branch: release

**Comment by vraravam** [comment]
The issue is that this line never returns the `files` as part of the struct: https://github.com/ferdium/ferdium-app/blob/develop/src/components/settings/services/EditServiceForm.tsx#L187

**Comment by pairofcrocs** [comment]
Experiencing the same on Windows 11 v6.2.1

**Comment by vraravam** [comment]
This is now fixed in the latest [6.2.2-nightly.1](https://github.com/ferdium/ferdium-app/releases/tag/v6.2.2-nightly.1)

**Comment by RJVB** [comment]
I just updated to 6.2.2 and still cannot add icons to my custom services (tried with png and svg files)!

**Comment by mikeyvt** [comment]
I'm on 6.2.3 and still can't save icons.

**Comment by RJVB** [comment]
On Friday January 06 2023 07:57:56 mikeyvt wrote:
>I'm on 6.2.3 and still can't save icons.  

Nice way of learning that there's an update ... but it turns out that 6.2.2 does allow me to save custom icons. As long as they're SVG AND square. Maybe they just need to be square, I haven't tried that.

I've used Inkscape to convert my PNG icons to SVG (with the bitmap embedded, no need for fancy tracing jobs).

**Comment by mikeyvt** [comment]
> 
Thanks.  I'll try to convert the file then and see if that works.

@RJVB which SVG file type did you save it as?  Trying to figure out how to save it with BMP embedded.  
![image](https://user-images.githubusercontent.com/33258406/211088005-c3adb516-cdef-4e92-a526-484ad119d163.png)
